[package]
name = "cotengrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "cotengrust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19"

[dependencies.bit-set]
version = "0.5"

[dependencies.rustc-hash]
version = "1.1"

[profile.release]
overflow-checks = true
lto = "fat"
